apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: monitoring
  labels:
    app: grafana
type: Opaque
data:
  # Base64 encoded admin password (admin123)
  admin-password: YWRtaW4xMjM=
